kind = "web"
previewPath = "/"
title = "Football Athletik App"
version = "1.0.0"
id = "football-athletik-app"

[[services]]
localPort = 5000
name = "Football Athletik App"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/athletik && streamlit run app.py --server.port 5000"
